name: ExtendedChests
main: me.noeffort.extendedchests.Main
version: 0.5.0

description: Expand the range of your chests today!
authors: [NoEffort, Air_neko]

commands:
  extendedchest:
    aliases: exchest
    description: Main command for the plugin.
    usage: "Usage: /<command>"